### ISSUE TITLE
Using values greater than one with FeedbackDelay

### ISSUE THREAD

**Issue by brokyo** [Tonejs/Tone.js#280]
I'm working on something that requires I use seconds rather than any kind of musical timing on a `FeedbackDelay` node. From what I understand of the docs delay nodes should accept number values and read them as seconds however whenever I try to pass a number greater than one I get:

`Delay.delayTime.value [x] outside nominal range [0, 1]; value will be clamped.`

On `Tone.Delay` you can increase `maxDelay` and get higher delay times but that doesn't seem to be and option here. Is there something I'm misunderstanding in the docs? 

https://jsfiddle.net/wL22zLbx/4/

**Comment by tambien** [comment]
Thanks for the issue. Should be fixed now: if a delayTime is passed into the constructor which is greater than the maxDelay, it will take the larger of the two. 

Here's a verification using the latest dev build: https://jsfiddle.net/wL22zLbx/6/

**Comment by Smona** [comment]
What version is this fixed in? I'm having the same problem in 0.11.11. My application sets the delay value over time rather than passing it into the constructor. Will that require a separate fix?
![2018-02-15_01-36-24](https://user-images.githubusercontent.com/7091399/36245424-a6cd660c-11f0-11e8-80bf-4abcc4bdb5b3.png)

**Comment by tambien** [comment]
@Smona good point. i've just updated FeedbackDelay so that you can pass in maxDelay in the options object. if all the tests pass, this will be available if you `npm install tone@next` which gets the latest dev build.

**Comment by Smona** [comment]
Heya @tambien, looks like this still isn't working in 13.3.11. Looks like a default maxDelay is set, but hasn't been added to the keys in the call to Tone.defaults of FeedbackDelay, so it can't be used.

I'm working around this currently by passing 100s as the delay time at creation and then setting the correct value afterward, but this behavior is nonobvious and undocumented. It would be better if either maxDelay worked and was properly documented, or if Tone automatically set the maxDelay to the largest value possible so the developer doesn't have to worry about it.

**Comment by tambien** [comment]
maxDelay can only be set at the time of construction that's why it doesn't have a getter/setter. it appears to be working for me: https://jsfiddle.net/wL22zLbx/15/

delayTime and maxDelay are set in [this line](https://github.com/Tonejs/Tone.js/blob/3d1202043a1171c2d12c4b5a8cc197f80df31940/Tone/effect/FeedbackDelay.js#L32). i think it might be a huge memory drain to set the maxDelay to a large time, since i'm pretty sure web audio allocates that size array under the hood. so i think it's better to air on the side of smaller maxDelay when possible. 

doc improvements and PRs are definitely welcome if you think there's a way to clarify the way that it works

**Comment by Smona** [comment]
Ohh interesting, I didn't even know about the object syntax for constructors. The bit about memory allocation is also good to know. I'll probably start contributing soon when I have some free time, since my project is going to end up using almost the whole library :grinning: thanks for the awesome work on tone!
